version: "3.9"

services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    # image: kakavic/nginx-php
    env_file: resources/.env
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    env_file: resources/.env
    volumes:
      - "dbdata:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
  redis:
    image: redis
volumes:
  dbdata: