name: Docker Image CI (Apache-PHP)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'apache-php/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      working-directory: ./apache-php
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/apache-php --push
