name: Docker Image CI (Nginx-PHP)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'nginx-php/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      run: docker build ./nginx-php --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/nginx-php
